export { default as AddEditClientTemplate, type Employee } from '@src/components/templates/AddEditClientTemplate/AddEditClientTemplate';
export { AuthTemplate } from '@src/components/templates/AuthTemplate/AuthTemplate';
export { default as ClientDetailsTemplate, type ClientDetail, type InvoiceItem, type VisitItem } from '@src/components/templates/ClientDetailsTemplate/ClientDetailsTemplate';
export { default as ClientsTemplate } from '@src/components/templates/ClientsTemplate/ClientsTemplate';
export { default as CreateDiscountTemplate } from '@src/components/templates/CreateDiscountTemplate/CreateDiscountTemplate';
export { default as CreateInvoiceTemplate } from '@src/components/templates/CreateInvoiceTemplate/CreateInvoiceTemplate';
export { default as DiscountDetailsTemplate } from '@src/components/templates/DiscountDetailsTemplate/DiscountDetailsTemplate';
export { default as DiscountsTemplate } from '@src/components/templates/DiscountsTemplate/DiscountsTemplate';
export { MainTemplate } from '@src/components/templates/MainTemplate/MainTemplate';
export { default as ReviewInvoiceTemplate } from '@src/components/templates/ReviewInvoiceTemplate/ReviewInvoiceTemplate';
export { SalesHomeTemplate } from '@src/components/templates/SalesHomeTemplate/SalesHomeTemplate';
export { default as ReceiptDetailsTemplate, type ReceiptDetail } from '@src/components/templates/ReceiptDetailsTemplate/ReceiptDetailsTemplate';
export { default as ReceiptsCenterTemplate } from '@src/components/templates/ReceiptsCenterTemplate/ReceiptsCenterTemplate';
export { default as CollectionsTemplate } from '@src/components/templates/CollectionsTemplate/CollectionsTemplate';
export { default as InventoryTemplate } from '@src/components/templates/InventoryTemplate/InventoryTemplate';
export { default as VisitForumTemplate } from '@src/components/templates/VisitForumTemplate/VisitForumTemplate';
export { default as VisitDetailsTemplate } from '@src/components/templates/VisitDetailsTemplate/VisitDetailsTemplate';
export { default as AddVisitTemplate } from '@src/components/templates/AddVisitTemplate/AddVisitTemplate';
