import BackIcon from "./BackIcon.svg";
import home from "./home.svg";
import eye from "./eye.svg";
import arrowup from "./arrowup.svg";
import calendar from "./calendar.svg";
import creditCard from "./creditCard.svg";
import creditCardGray from "./creditCardGray.svg";
import FeaturedIcon from "./FeaturedIcon.svg";
import fileText from "./fileText.svg";
import Filters from "./Filters.svg";
import HomeChart from "./HomeChart.svg";
import lifeBuoy from "./lifeBuoy.svg";
import lock from "./lock.svg";
import map from "./map.svg";
import mapcolor from "./mapcolor.svg";
import MenuIcon from "./MenuIcon.svg";
import percent from "./percent.svg";
import phone from "./phone.svg";
import phoneColor from "./phoneColor.svg";
import remove from "./remove.svg";
import search from "./search.svg";
import shoppingBag from "./shoppingBag.svg";
import shoppingGray from "./shoppingGray.svg";
import user from "./user.svg";
import users from "./users.svg";
import closeIcon from './closeIcon.svg'

export class Components {
    static backIcon = BackIcon;
    static home = home;
    static eye = eye;
    static arrowup = arrowup;
    static calendar = calendar;
    static creditCard = creditCard;
    static creditCardGray = creditCardGray;
    static featuredIcon = FeaturedIcon;
    static fileText = fileText;
    static filters = Filters;
    static homeChart = HomeChart;
    static lifeBuoy = lifeBuoy;
    static lock = lock;
    static map = map;
    static mapcolor = mapcolor;
    static menuIcon = MenuIcon;
    static percent = percent;
    static phone = phone;
    static phoneColor = phoneColor;
    static remove = remove;
    static search = search;
    static shoppingBag = shoppingBag;
    static shoppingGray = shoppingGray;
    static user = user;
    static users = users;
    static closeIcon =closeIcon
}
