export const Routes = {
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  HOME: 'Home',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  RESET_CODE: 'ResetCode',
  NEW_PASSWORD: 'NewPassword',
  CREATE_INVOICE:"CreateInvoice",
  CAMERA_SCREEN :'CameraScreen',
  CONFIRM_INVOICE:'ConfirmInvoice',
  DISCOUNTS:'Discounts',
  CLIENTS:'Clients',
  CREATE_DISCOUNTS:'CreateDiscounts',
  DISCOUNT_DETAILS: 'DiscountDetails',
  ADD_CLIENT: 'AddClient',
  EDIT_CLIENT: 'EditClient',
  CLIENT_DETAILS: 'ClientDetails',
  RECEIPTS_CENTER: 'ReceiptsCenter',
  RECEIPT_DETAILS: 'ReceiptDetails',
  COLLECTIONS: 'Collections',
  INVENTORY: 'Inventory',
  VISIT_FORUM: 'VisitForum',
  VISIT_DETAILS: 'VisitDetails',
  ADD_VISIT: 'AddVisit',
};
